# Runs Deployment health checker for UTP Synthetics in the PPE environment

jobs:
- job: serverjob
  pool: server
  steps:
  - task: DeploymentHealthCheckerForUTPSyntheticsPPE@0
    inputs:
        connectedServiceDHC: 'DHC-PPE-OneITVSO'