jobs:
- job: serverjob
  pool: server
  steps:
  - task: DeploymentHealthCheckerForUTPSyntheticsPPE-v2@0
    displayName: 'DeploymentHealthCheckerForUTPSyntheticsPPE-v2'
    inputs:
      azureSubscription: 'f085edb3-dfc8-49ec-b9eb-d2527f659bfe'