jobs:
- job: serverjob
  pool: server
  steps:
  - task: DeploymentHealthCheckerForUTPSyntheticsPPE@0
    displayName: 'DeploymentHealthCheckerForUTPSyntheticsPPE'
    inputs:
      azureSubscription: 'DHC-PPE-OneITVSO'